/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.groupbyinc.retailapi.JSON;

/**
 * Contains debug info associated to response.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-21T09:40:02.999263865-04:00[America/Toronto]")
public class DebugDto {
  public static final String SERIALIZED_NAME_RAW_SEARCH_REQUEST = "rawSearchRequest";
  @SerializedName(SERIALIZED_NAME_RAW_SEARCH_REQUEST)
  private List<Object> rawSearchRequest;

  public static final String SERIALIZED_NAME_RAW_SEARCH_RESPONSE = "rawSearchResponse";
  @SerializedName(SERIALIZED_NAME_RAW_SEARCH_RESPONSE)
  private List<Object> rawSearchResponse;

  public DebugDto() {
  }

  public DebugDto rawSearchRequest(List<Object> rawSearchRequest) {
    
    this.rawSearchRequest = rawSearchRequest;
    return this;
  }

  public DebugDto addRawSearchRequestItem(Object rawSearchRequestItem) {
    if (this.rawSearchRequest == null) {
      this.rawSearchRequest = new ArrayList<>();
    }
    this.rawSearchRequest.add(rawSearchRequestItem);
    return this;
  }

   /**
   * Search request in raw format executed internally against search engine.
   * @return rawSearchRequest
  **/
  @javax.annotation.Nullable
  public List<Object> getRawSearchRequest() {
    return rawSearchRequest;
  }


  public void setRawSearchRequest(List<Object> rawSearchRequest) {
    this.rawSearchRequest = rawSearchRequest;
  }


  public DebugDto rawSearchResponse(List<Object> rawSearchResponse) {
    
    this.rawSearchResponse = rawSearchResponse;
    return this;
  }

  public DebugDto addRawSearchResponseItem(Object rawSearchResponseItem) {
    if (this.rawSearchResponse == null) {
      this.rawSearchResponse = new ArrayList<>();
    }
    this.rawSearchResponse.add(rawSearchResponseItem);
    return this;
  }

   /**
   * Search response in raw format received internally from search engine.
   * @return rawSearchResponse
  **/
  @javax.annotation.Nullable
  public List<Object> getRawSearchResponse() {
    return rawSearchResponse;
  }


  public void setRawSearchResponse(List<Object> rawSearchResponse) {
    this.rawSearchResponse = rawSearchResponse;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DebugDto debugDto = (DebugDto) o;
    return Objects.equals(this.rawSearchRequest, debugDto.rawSearchRequest) &&
        Objects.equals(this.rawSearchResponse, debugDto.rawSearchResponse);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rawSearchRequest, rawSearchResponse);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DebugDto {\n");
    sb.append("    rawSearchRequest: ").append(toIndentedString(rawSearchRequest)).append("\n");
    sb.append("    rawSearchResponse: ").append(toIndentedString(rawSearchResponse)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("rawSearchRequest");
    openapiFields.add("rawSearchResponse");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to DebugDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DebugDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DebugDto is not found in the empty JSON string", DebugDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DebugDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DebugDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("rawSearchRequest") != null && !jsonObj.get("rawSearchRequest").isJsonNull() && !jsonObj.get("rawSearchRequest").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `rawSearchRequest` to be an array in the JSON string but got `%s`", jsonObj.get("rawSearchRequest").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("rawSearchResponse") != null && !jsonObj.get("rawSearchResponse").isJsonNull() && !jsonObj.get("rawSearchResponse").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `rawSearchResponse` to be an array in the JSON string but got `%s`", jsonObj.get("rawSearchResponse").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DebugDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DebugDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DebugDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DebugDto.class));

       return (TypeAdapter<T>) new TypeAdapter<DebugDto>() {
           @Override
           public void write(JsonWriter out, DebugDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DebugDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DebugDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DebugDto
  * @throws IOException if the JSON string is invalid with respect to DebugDto
  */
  public static DebugDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DebugDto.class);
  }

 /**
  * Convert an instance of DebugDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

