/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupbyinc.retailapi.model.NavigationDto;
import com.groupbyinc.retailapi.model.SearchRequestDto;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.groupbyinc.retailapi.JSON;

/**
 * Facet search response representation.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-21T09:40:02.999263865-04:00[America/Toronto]")
public class FacetSearchResponseDto {
  public static final String SERIALIZED_NAME_ORIGINAL_REQUEST = "originalRequest";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_REQUEST)
  private SearchRequestDto originalRequest;

  public static final String SERIALIZED_NAME_AVAILABLE_NAVIGATION = "availableNavigation";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_NAVIGATION)
  private NavigationDto availableNavigation;

  public FacetSearchResponseDto() {
  }

  public FacetSearchResponseDto originalRequest(SearchRequestDto originalRequest) {
    
    this.originalRequest = originalRequest;
    return this;
  }

   /**
   * Get originalRequest
   * @return originalRequest
  **/
  @javax.annotation.Nonnull
  public SearchRequestDto getOriginalRequest() {
    return originalRequest;
  }


  public void setOriginalRequest(SearchRequestDto originalRequest) {
    this.originalRequest = originalRequest;
  }


  public FacetSearchResponseDto availableNavigation(NavigationDto availableNavigation) {
    
    this.availableNavigation = availableNavigation;
    return this;
  }

   /**
   * Get availableNavigation
   * @return availableNavigation
  **/
  @javax.annotation.Nonnull
  public NavigationDto getAvailableNavigation() {
    return availableNavigation;
  }


  public void setAvailableNavigation(NavigationDto availableNavigation) {
    this.availableNavigation = availableNavigation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FacetSearchResponseDto facetSearchResponseDto = (FacetSearchResponseDto) o;
    return Objects.equals(this.originalRequest, facetSearchResponseDto.originalRequest) &&
        Objects.equals(this.availableNavigation, facetSearchResponseDto.availableNavigation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(originalRequest, availableNavigation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FacetSearchResponseDto {\n");
    sb.append("    originalRequest: ").append(toIndentedString(originalRequest)).append("\n");
    sb.append("    availableNavigation: ").append(toIndentedString(availableNavigation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("originalRequest");
    openapiFields.add("availableNavigation");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("originalRequest");
    openapiRequiredFields.add("availableNavigation");
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to FacetSearchResponseDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!FacetSearchResponseDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FacetSearchResponseDto is not found in the empty JSON string", FacetSearchResponseDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!FacetSearchResponseDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `FacetSearchResponseDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : FacetSearchResponseDto.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `originalRequest`
      SearchRequestDto.validateJsonElement(jsonObj.get("originalRequest"));
      // validate the required field `availableNavigation`
      NavigationDto.validateJsonElement(jsonObj.get("availableNavigation"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FacetSearchResponseDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FacetSearchResponseDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FacetSearchResponseDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FacetSearchResponseDto.class));

       return (TypeAdapter<T>) new TypeAdapter<FacetSearchResponseDto>() {
           @Override
           public void write(JsonWriter out, FacetSearchResponseDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public FacetSearchResponseDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FacetSearchResponseDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FacetSearchResponseDto
  * @throws IOException if the JSON string is invalid with respect to FacetSearchResponseDto
  */
  public static FacetSearchResponseDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FacetSearchResponseDto.class);
  }

 /**
  * Convert an instance of FacetSearchResponseDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

