/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.groupbyinc.retailapi.JSON;

/**
 * Information regarding where the page of results starts and ends.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-21T09:51:40.117075497-04:00[America/Toronto]")
public class PageInfoDto {
  public static final String SERIALIZED_NAME_RECORD_START = "recordStart";
  @SerializedName(SERIALIZED_NAME_RECORD_START)
  private Long recordStart;

  public static final String SERIALIZED_NAME_RECORD_END = "recordEnd";
  @SerializedName(SERIALIZED_NAME_RECORD_END)
  private Long recordEnd;

  public PageInfoDto() {
  }

  public PageInfoDto recordStart(Long recordStart) {
    
    this.recordStart = recordStart;
    return this;
  }

   /**
   * Where in the list of products the page begins.
   * minimum: 0
   * @return recordStart
  **/
  @javax.annotation.Nullable
  public Long getRecordStart() {
    return recordStart;
  }


  public void setRecordStart(Long recordStart) {
    this.recordStart = recordStart;
  }


  public PageInfoDto recordEnd(Long recordEnd) {
    
    this.recordEnd = recordEnd;
    return this;
  }

   /**
   * Where in the list of products the page ends.
   * minimum: 1
   * @return recordEnd
  **/
  @javax.annotation.Nullable
  public Long getRecordEnd() {
    return recordEnd;
  }


  public void setRecordEnd(Long recordEnd) {
    this.recordEnd = recordEnd;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PageInfoDto pageInfoDto = (PageInfoDto) o;
    return Objects.equals(this.recordStart, pageInfoDto.recordStart) &&
        Objects.equals(this.recordEnd, pageInfoDto.recordEnd);
  }

  @Override
  public int hashCode() {
    return Objects.hash(recordStart, recordEnd);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PageInfoDto {\n");
    sb.append("    recordStart: ").append(toIndentedString(recordStart)).append("\n");
    sb.append("    recordEnd: ").append(toIndentedString(recordEnd)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("recordStart");
    openapiFields.add("recordEnd");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PageInfoDto
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PageInfoDto.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PageInfoDto is not found in the empty JSON string", PageInfoDto.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PageInfoDto.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PageInfoDto` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PageInfoDto.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PageInfoDto' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PageInfoDto> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PageInfoDto.class));

       return (TypeAdapter<T>) new TypeAdapter<PageInfoDto>() {
           @Override
           public void write(JsonWriter out, PageInfoDto value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PageInfoDto read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PageInfoDto given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PageInfoDto
  * @throws IOException if the JSON string is invalid with respect to PageInfoDto
  */
  public static PageInfoDto fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PageInfoDto.class);
  }

 /**
  * Convert an instance of PageInfoDto to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

