/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupbyinc.retailapi.model.PriceInfoPriceRangeOriginalPrice;
import com.groupbyinc.retailapi.model.PriceInfoPriceRangePrice;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.groupbyinc.retailapi.JSON;

/**
 * PriceInfoPriceRange
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-21T09:40:02.999263865-04:00[America/Toronto]")
public class PriceInfoPriceRange {
  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private PriceInfoPriceRangePrice price;

  public static final String SERIALIZED_NAME_ORIGINAL_PRICE = "originalPrice";
  @SerializedName(SERIALIZED_NAME_ORIGINAL_PRICE)
  private PriceInfoPriceRangeOriginalPrice originalPrice;

  public PriceInfoPriceRange() {
  }

  public PriceInfoPriceRange price(PriceInfoPriceRangePrice price) {
    
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @javax.annotation.Nullable
  public PriceInfoPriceRangePrice getPrice() {
    return price;
  }


  public void setPrice(PriceInfoPriceRangePrice price) {
    this.price = price;
  }


  public PriceInfoPriceRange originalPrice(PriceInfoPriceRangeOriginalPrice originalPrice) {
    
    this.originalPrice = originalPrice;
    return this;
  }

   /**
   * Get originalPrice
   * @return originalPrice
  **/
  @javax.annotation.Nullable
  public PriceInfoPriceRangeOriginalPrice getOriginalPrice() {
    return originalPrice;
  }


  public void setOriginalPrice(PriceInfoPriceRangeOriginalPrice originalPrice) {
    this.originalPrice = originalPrice;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PriceInfoPriceRange priceInfoPriceRange = (PriceInfoPriceRange) o;
    return Objects.equals(this.price, priceInfoPriceRange.price) &&
        Objects.equals(this.originalPrice, priceInfoPriceRange.originalPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(price, originalPrice);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PriceInfoPriceRange {\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    originalPrice: ").append(toIndentedString(originalPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("price");
    openapiFields.add("originalPrice");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to PriceInfoPriceRange
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PriceInfoPriceRange.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PriceInfoPriceRange is not found in the empty JSON string", PriceInfoPriceRange.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PriceInfoPriceRange.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PriceInfoPriceRange` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `price`
      if (jsonObj.get("price") != null && !jsonObj.get("price").isJsonNull()) {
        PriceInfoPriceRangePrice.validateJsonElement(jsonObj.get("price"));
      }
      // validate the optional field `originalPrice`
      if (jsonObj.get("originalPrice") != null && !jsonObj.get("originalPrice").isJsonNull()) {
        PriceInfoPriceRangeOriginalPrice.validateJsonElement(jsonObj.get("originalPrice"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PriceInfoPriceRange.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PriceInfoPriceRange' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PriceInfoPriceRange> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PriceInfoPriceRange.class));

       return (TypeAdapter<T>) new TypeAdapter<PriceInfoPriceRange>() {
           @Override
           public void write(JsonWriter out, PriceInfoPriceRange value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PriceInfoPriceRange read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of PriceInfoPriceRange given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of PriceInfoPriceRange
  * @throws IOException if the JSON string is invalid with respect to PriceInfoPriceRange
  */
  public static PriceInfoPriceRange fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PriceInfoPriceRange.class);
  }

 /**
  * Convert an instance of PriceInfoPriceRange to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

