/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Order the products will appear in
 */
@JsonAdapter(SortDtoOrderDto.Adapter.class)
public enum SortDtoOrderDto {
  
  ASCENDING("Ascending"),
  
  DESCENDING("Descending");

  private String value;

  SortDtoOrderDto(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static SortDtoOrderDto fromValue(String value) {
    for (SortDtoOrderDto b : SortDtoOrderDto.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<SortDtoOrderDto> {
    @Override
    public void write(final JsonWriter jsonWriter, final SortDtoOrderDto enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public SortDtoOrderDto read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return SortDtoOrderDto.fromValue(value);
    }
  }
}

