/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ColorInfo
 */
public class ColorInfoTest {
    private final ColorInfo model = new ColorInfo();

    /**
     * Model tests for ColorInfo
     */
    @Test
    public void testColorInfo() {
        // TODO: test ColorInfo
    }

    /**
     * Test the property 'colorFamilies'
     */
    @Test
    public void colorFamiliesTest() {
        // TODO: test colorFamilies
    }

    /**
     * Test the property 'colors'
     */
    @Test
    public void colorsTest() {
        // TODO: test colors
    }

}
