/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupbyinc.retailapi.model.RuleVariant;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ExperimentVariant
 */
public class ExperimentVariantTest {
    private final ExperimentVariant model = new ExperimentVariant();

    /**
     * Model tests for ExperimentVariant
     */
    @Test
    public void testExperimentVariant() {
        // TODO: test ExperimentVariant
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ruleVariant'
     */
    @Test
    public void ruleVariantTest() {
        // TODO: test ruleVariant
    }

    /**
     * Test the property 'variantTriggerPercentage'
     */
    @Test
    public void variantTriggerPercentageTest() {
        // TODO: test variantTriggerPercentage
    }

}
