/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupbyinc.retailapi.model.NavigationDto;
import com.groupbyinc.retailapi.model.SearchRequestDto;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FacetSearchResponseDto
 */
public class FacetSearchResponseDtoTest {
    private final FacetSearchResponseDto model = new FacetSearchResponseDto();

    /**
     * Model tests for FacetSearchResponseDto
     */
    @Test
    public void testFacetSearchResponseDto() {
        // TODO: test FacetSearchResponseDto
    }

    /**
     * Test the property 'originalRequest'
     */
    @Test
    public void originalRequestTest() {
        // TODO: test originalRequest
    }

    /**
     * Test the property 'availableNavigation'
     */
    @Test
    public void availableNavigationTest() {
        // TODO: test availableNavigation
    }

}
