/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FieldMask
 */
public class FieldMaskTest {
    private final FieldMask model = new FieldMask();

    /**
     * Model tests for FieldMask
     */
    @Test
    public void testFieldMask() {
        // TODO: test FieldMask
    }

    /**
     * Test the property 'paths'
     */
    @Test
    public void pathsTest() {
        // TODO: test paths
    }

}
