/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PageInfoDto
 */
public class PageInfoDtoTest {
    private final PageInfoDto model = new PageInfoDto();

    /**
     * Model tests for PageInfoDto
     */
    @Test
    public void testPageInfoDto() {
        // TODO: test PageInfoDto
    }

    /**
     * Test the property 'recordStart'
     */
    @Test
    public void recordStartTest() {
        // TODO: test recordStart
    }

    /**
     * Test the property 'recordEnd'
     */
    @Test
    public void recordEndTest() {
        // TODO: test recordEnd
    }

}
