/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupbyinc.retailapi.model.PriceInfoPriceRangeOriginalPrice;
import com.groupbyinc.retailapi.model.PriceInfoPriceRangePrice;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PriceInfoPriceRange
 */
public class PriceInfoPriceRangeTest {
    private final PriceInfoPriceRange model = new PriceInfoPriceRange();

    /**
     * Model tests for PriceInfoPriceRange
     */
    @Test
    public void testPriceInfoPriceRange() {
        // TODO: test PriceInfoPriceRange
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'originalPrice'
     */
    @Test
    public void originalPriceTest() {
        // TODO: test originalPrice
    }

}
