/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PriceInfoPriceRangePrice
 */
public class PriceInfoPriceRangePriceTest {
    private final PriceInfoPriceRangePrice model = new PriceInfoPriceRangePrice();

    /**
     * Model tests for PriceInfoPriceRangePrice
     */
    @Test
    public void testPriceInfoPriceRangePrice() {
        // TODO: test PriceInfoPriceRangePrice
    }

    /**
     * Test the property 'minimum'
     */
    @Test
    public void minimumTest() {
        // TODO: test minimum
    }

    /**
     * Test the property 'exclusiveMinimum'
     */
    @Test
    public void exclusiveMinimumTest() {
        // TODO: test exclusiveMinimum
    }

    /**
     * Test the property 'maximum'
     */
    @Test
    public void maximumTest() {
        // TODO: test maximum
    }

    /**
     * Test the property 'exclusiveMaximum'
     */
    @Test
    public void exclusiveMaximumTest() {
        // TODO: test exclusiveMaximum
    }

}
