/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupbyinc.retailapi.model.FulfillmentInfo;
import com.groupbyinc.retailapi.model.Image;
import com.groupbyinc.retailapi.model.ProductCustomAttribute;
import com.groupbyinc.retailapi.model.ProductDtoAudience;
import com.groupbyinc.retailapi.model.ProductDtoAvailableTime;
import com.groupbyinc.retailapi.model.ProductDtoColorInfo;
import com.groupbyinc.retailapi.model.ProductDtoPriceInfo;
import com.groupbyinc.retailapi.model.ProductDtoPublishTime;
import com.groupbyinc.retailapi.model.ProductDtoRating;
import com.groupbyinc.retailapi.model.ProductDtoRetrievableFields;
import com.groupbyinc.retailapi.model.Promotion;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ProductDto
 */
public class ProductDtoTest {
    private final ProductDto model = new ProductDto();

    /**
     * Model tests for ProductDto
     */
    @Test
    public void testProductDto() {
        // TODO: test ProductDto
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'primaryProductId'
     */
    @Test
    public void primaryProductIdTest() {
        // TODO: test primaryProductId
    }

    /**
     * Test the property 'collectionMemberIds'
     */
    @Test
    public void collectionMemberIdsTest() {
        // TODO: test collectionMemberIds
    }

    /**
     * Test the property 'gtin'
     */
    @Test
    public void gtinTest() {
        // TODO: test gtin
    }

    /**
     * Test the property 'categories'
     */
    @Test
    public void categoriesTest() {
        // TODO: test categories
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'brands'
     */
    @Test
    public void brandsTest() {
        // TODO: test brands
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'languageCode'
     */
    @Test
    public void languageCodeTest() {
        // TODO: test languageCode
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'priceInfo'
     */
    @Test
    public void priceInfoTest() {
        // TODO: test priceInfo
    }

    /**
     * Test the property 'rating'
     */
    @Test
    public void ratingTest() {
        // TODO: test rating
    }

    /**
     * Test the property 'availableTime'
     */
    @Test
    public void availableTimeTest() {
        // TODO: test availableTime
    }

    /**
     * Test the property 'availability'
     */
    @Test
    public void availabilityTest() {
        // TODO: test availability
    }

    /**
     * Test the property 'availableQuantity'
     */
    @Test
    public void availableQuantityTest() {
        // TODO: test availableQuantity
    }

    /**
     * Test the property 'fulfillmentInfos'
     */
    @Test
    public void fulfillmentInfosTest() {
        // TODO: test fulfillmentInfos
    }

    /**
     * Test the property 'uri'
     */
    @Test
    public void uriTest() {
        // TODO: test uri
    }

    /**
     * Test the property 'images'
     */
    @Test
    public void imagesTest() {
        // TODO: test images
    }

    /**
     * Test the property 'audience'
     */
    @Test
    public void audienceTest() {
        // TODO: test audience
    }

    /**
     * Test the property 'colorInfo'
     */
    @Test
    public void colorInfoTest() {
        // TODO: test colorInfo
    }

    /**
     * Test the property 'sizes'
     */
    @Test
    public void sizesTest() {
        // TODO: test sizes
    }

    /**
     * Test the property 'materials'
     */
    @Test
    public void materialsTest() {
        // TODO: test materials
    }

    /**
     * Test the property 'patterns'
     */
    @Test
    public void patternsTest() {
        // TODO: test patterns
    }

    /**
     * Test the property 'conditions'
     */
    @Test
    public void conditionsTest() {
        // TODO: test conditions
    }

    /**
     * Test the property 'publishTime'
     */
    @Test
    public void publishTimeTest() {
        // TODO: test publishTime
    }

    /**
     * Test the property 'retrievableFields'
     */
    @Test
    public void retrievableFieldsTest() {
        // TODO: test retrievableFields
    }

    /**
     * Test the property 'promotions'
     */
    @Test
    public void promotionsTest() {
        // TODO: test promotions
    }

    /**
     * Test the property 'variants'
     */
    @Test
    public void variantsTest() {
        // TODO: test variants
    }

}
