/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.annotations.SerializedName;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for QueryPatternTriggerType
 */
public class QueryPatternTriggerTypeTest {
    /**
     * Model tests for QueryPatternTriggerType
     */
    @Test
    public void testQueryPatternTriggerType() {
        // TODO: test QueryPatternTriggerType
    }

}
