/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupbyinc.retailapi.model.Filter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RecommendationsRequest
 */
public class RecommendationsRequestTest {
    private final RecommendationsRequest model = new RecommendationsRequest();

    /**
     * Model tests for RecommendationsRequest
     */
    @Test
    public void testRecommendationsRequest() {
        // TODO: test RecommendationsRequest
    }

    /**
     * Test the property 'collection'
     */
    @Test
    public void collectionTest() {
        // TODO: test collection
    }

    /**
     * Test the property 'visitorId'
     */
    @Test
    public void visitorIdTest() {
        // TODO: test visitorId
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'loginId'
     */
    @Test
    public void loginIdTest() {
        // TODO: test loginId
    }

    /**
     * Test the property 'productID'
     */
    @Test
    public void productIDTest() {
        // TODO: test productID
    }

    /**
     * Test the property 'fields'
     */
    @Test
    public void fieldsTest() {
        // TODO: test fields
    }

    /**
     * Test the property 'filters'
     */
    @Test
    public void filtersTest() {
        // TODO: test filters
    }

    /**
     * Test the property 'rawFilter'
     */
    @Test
    public void rawFilterTest() {
        // TODO: test rawFilter
    }

    /**
     * Test the property 'placement'
     */
    @Test
    public void placementTest() {
        // TODO: test placement
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'strictFiltering'
     */
    @Test
    public void strictFilteringTest() {
        // TODO: test strictFiltering
    }

}
