/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupbyinc.retailapi.model.DebugDto;
import com.groupbyinc.retailapi.model.Experiment;
import com.groupbyinc.retailapi.model.Metadata;
import com.groupbyinc.retailapi.model.NavigationDto;
import com.groupbyinc.retailapi.model.PageInfoDto;
import com.groupbyinc.retailapi.model.RecordDto;
import com.groupbyinc.retailapi.model.SearchMetadataDto;
import com.groupbyinc.retailapi.model.SearchRequestDto;
import com.groupbyinc.retailapi.model.TemplateDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchResponseDto
 */
public class SearchResponseDtoTest {
    private final SearchResponseDto model = new SearchResponseDto();

    /**
     * Model tests for SearchResponseDto
     */
    @Test
    public void testSearchResponseDto() {
        // TODO: test SearchResponseDto
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'area'
     */
    @Test
    public void areaTest() {
        // TODO: test area
    }

    /**
     * Test the property 'query'
     */
    @Test
    public void queryTest() {
        // TODO: test query
    }

    /**
     * Test the property 'correctedQuery'
     */
    @Test
    public void correctedQueryTest() {
        // TODO: test correctedQuery
    }

    /**
     * Test the property 'biasingProfile'
     */
    @Test
    public void biasingProfileTest() {
        // TODO: test biasingProfile
    }

    /**
     * Test the property 'biasingProfileAppliedId'
     */
    @Test
    public void biasingProfileAppliedIdTest() {
        // TODO: test biasingProfileAppliedId
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'originalRequest'
     */
    @Test
    public void originalRequestTest() {
        // TODO: test originalRequest
    }

    /**
     * Test the property 'records'
     */
    @Test
    public void recordsTest() {
        // TODO: test records
    }

    /**
     * Test the property 'totalRecordCount'
     */
    @Test
    public void totalRecordCountTest() {
        // TODO: test totalRecordCount
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'pageInfo'
     */
    @Test
    public void pageInfoTest() {
        // TODO: test pageInfo
    }

    /**
     * Test the property 'availableNavigation'
     */
    @Test
    public void availableNavigationTest() {
        // TODO: test availableNavigation
    }

    /**
     * Test the property 'selectedNavigation'
     */
    @Test
    public void selectedNavigationTest() {
        // TODO: test selectedNavigation
    }

    /**
     * Test the property 'redirect'
     */
    @Test
    public void redirectTest() {
        // TODO: test redirect
    }

    /**
     * Test the property 'experiments'
     */
    @Test
    public void experimentsTest() {
        // TODO: test experiments
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'empty'
     */
    @Test
    public void emptyTest() {
        // TODO: test empty
    }

    /**
     * Test the property 'siteParams'
     */
    @Test
    public void siteParamsTest() {
        // TODO: test siteParams
    }

    /**
     * Test the property 'debug'
     */
    @Test
    public void debugTest() {
        // TODO: test debug
    }

    /**
     * Test the property 'warnings'
     */
    @Test
    public void warningsTest() {
        // TODO: test warnings
    }

    /**
     * Test the property 'includeExpandedResults'
     */
    @Test
    public void includeExpandedResultsTest() {
        // TODO: test includeExpandedResults
    }

    /**
     * Test the property 'facetLimit'
     */
    @Test
    public void facetLimitTest() {
        // TODO: test facetLimit
    }

    /**
     * Test the property 'redirectMetadata'
     */
    @Test
    public void redirectMetadataTest() {
        // TODO: test redirectMetadata
    }

}
