/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupbyinc.retailapi.model.AttributeSuggestion;
import com.groupbyinc.retailapi.model.SearchResultsStats;
import com.groupbyinc.retailapi.model.SearchTerms;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchResults
 */
public class SearchResultsTest {
    private final SearchResults model = new SearchResults();

    /**
     * Model tests for SearchResults
     */
    @Test
    public void testSearchResults() {
        // TODO: test SearchResults
    }

    /**
     * Test the property 'stats'
     */
    @Test
    public void statsTest() {
        // TODO: test stats
    }

    /**
     * Test the property 'searchTerms'
     */
    @Test
    public void searchTermsTest() {
        // TODO: test searchTerms
    }

    /**
     * Test the property 'extendedAttributes'
     */
    @Test
    public void extendedAttributesTest() {
        // TODO: test extendedAttributes
    }

    /**
     * Test the property 'attributeResults'
     */
    @Test
    public void attributeResultsTest() {
        // TODO: test attributeResults
    }

    /**
     * Test the property 'siteFilter'
     */
    @Test
    public void siteFilterTest() {
        // TODO: test siteFilter
    }

}
