/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SearchMetadataDto
 */
public class SearchMetadataDtoTest {
    private final SearchMetadataDto model = new SearchMetadataDto();

    /**
     * Model tests for SearchMetadataDto
     */
    @Test
    public void testSearchMetadataDto() {
        // TODO: test SearchMetadataDto
    }

    /**
     * Test the property 'searchAttributionToken'
     */
    @Test
    public void searchAttributionTokenTest() {
        // TODO: test searchAttributionToken
    }

    /**
     * Test the property 'cached'
     */
    @Test
    public void cachedTest() {
        // TODO: test cached
    }

    /**
     * Test the property 'totalTime'
     */
    @Test
    public void totalTimeTest() {
        // TODO: test totalTime
    }

}
