/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupbyinc.retailapi.model.ModelBoolean;
import com.groupbyinc.retailapi.model.NavigationTypeDto;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SelectedRefinementDto
 */
public class SelectedRefinementDtoTest {
    private final SelectedRefinementDto model = new SelectedRefinementDto();

    /**
     * Model tests for SelectedRefinementDto
     */
    @Test
    public void testSelectedRefinementDto() {
        // TODO: test SelectedRefinementDto
    }

    /**
     * Test the property 'navigationName'
     */
    @Test
    public void navigationNameTest() {
        // TODO: test navigationName
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'low'
     */
    @Test
    public void lowTest() {
        // TODO: test low
    }

    /**
     * Test the property 'high'
     */
    @Test
    public void highTest() {
        // TODO: test high
    }

    /**
     * Test the property 'source'
     */
    @Test
    public void sourceTest() {
        // TODO: test source
    }

    /**
     * Test the property 'or'
     */
    @Test
    public void orTest() {
        // TODO: test or
    }

}
