/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.groupbyinc.retailapi.model.TemplateDtoTriggerSet;
import com.groupbyinc.retailapi.model.ZoneDto;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TemplateDto
 */
public class TemplateDtoTest {
    private final TemplateDto model = new TemplateDto();

    /**
     * Model tests for TemplateDto
     */
    @Test
    public void testTemplateDto() {
        // TODO: test TemplateDto
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'ruleName'
     */
    @Test
    public void ruleNameTest() {
        // TODO: test ruleName
    }

    /**
     * Test the property 'triggerSet'
     */
    @Test
    public void triggerSetTest() {
        // TODO: test triggerSet
    }

    /**
     * Test the property 'zones'
     */
    @Test
    public void zonesTest() {
        // TODO: test zones
    }

}
