/*
 * GroupBy Retail
 * GroupBy Retail API
 *
 * The version of the OpenAPI document: 0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.groupbyinc.retailapi.api;

import com.groupbyinc.retailapi.ApiException;
import com.groupbyinc.retailapi.model.PredictResults;
import com.groupbyinc.retailapi.model.RecommendationsErrorResponse;
import com.groupbyinc.retailapi.model.RecommendationsRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for RecommendationsApiApi
 */
@Disabled
public class RecommendationsApiApiTest {

    private final RecommendationsApiApi api = new RecommendationsApiApi();

    /**
     * Provide Recommendations AI functionality.
     *
     * Perform a recommendation request against the GroupBy Retail Recommendations API.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void predictTest() throws ApiException {
        String xGroupbyCustomerId = null;
        RecommendationsRequest recommendationsRequest = null;
        PredictResults response = api.predict(xGroupbyCustomerId, recommendationsRequest);
        // TODO: test validations
    }

    /**
     * Provide Recommendations AI functionality.
     *
     * Perform a recommendation request against the GroupBy Retail Recommendations API.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void predictV2Test() throws ApiException {
        String xGroupbyCustomerId = null;
        RecommendationsRequest recommendationsRequest = null;
        PredictResults response = api.predictV2(xGroupbyCustomerId, recommendationsRequest);
        // TODO: test validations
    }

}
